name: create-release
on: push
  # push:
  #   tags: ['v*.*.*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build PK3s
        run: |
          pwd
          ls
          cd patches
          (cd common; zip -r ../hh_patch_common.pk3 *)
          (cd heretic; zip -r ../hh_patch_heretic.pk3 *)
          (cd hexen; zip -r ../hh_patch_hexen.pk3 *)
          (cd hexdd; zip -r ../hh_patch_hexdd.pk3 *)
          (cd fr; zip -r ../hh_patch_fr.pk3 *)
          (cd vog; zip -r ../hh_patch_vog.pk3 *)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: hh_patch_pk3s
          path: patches/*.pk3
          if-no-files-found: error